absolute_urls: false

home:
  alias: '/home'

pages:
  theme: quark
  markdown:
    extra: false
    twig: true
  process:
    markdown: true
    twig: true

cache:
  enabled: true
  check:
    method: file
  driver: auto
  prefix: 'g'

twig:
  cache: false
  debug: false
  auto_reload: true
  autoescape: true

assets:
  css_pipeline: false
  css_minify: true
  css_rewrite: true
  js_pipeline: false
  js_module_pipeline: false
  js_minify: true

errors:
  display: true
  log: true

debugger:
  enabled: false
  twig: false
  shutdown:
    close_connection: true
gpm:
  verify_peer: true

 